export enum CommentTopicEnum {
  QUALITY = "QUALITY",
  RECEIPT = "RECEIPT",
  GENERAL_SATISFACTION = "GENERAL_SATISFACTION",
  DELIVERY = "DELIVERY",
  RECOMMENDATION = "RECOMMENDATION",
  EXPECTATION = "EXPECTATION",
}
