export enum CommentTopicEnum {
  QUALITY = "QUALITY",
  RECEIVEMENT = "RECEIVEMENT",
  SATISFIED = "SATISFIED",
  DELIVERY = "DELIVERY",
  RECOMMENDATION = "RECOMMENDATION",
  EXPECTATION = "EXPECTATION",
  OTHERS = "OTHERS",
  COST_BENEFIT = "COSTBENEFIT",
}
