export enum CommentTopicEnum {
  QUALITY = "QUALIDADE",
  RECEIPT = "RECEBIMENTO",
  GENERAL_SATISFACTION = "SATISFAÇÃO",
  DELIVERY = "ENTREGA",
  RECOMMENDATION = "RECOMENDAÇÃO",
  EXPECTATION = "EXPECTATIVA",
  OTHERS = "OUTROS",
  COST_BENEFIT = "CUSTO BENEFÍCIO",
}
